import { allOperations } from './document';

/**
 * The API reference in docs/04-api-spec.md, generated from the same operation list the contract
 * test holds every route to, so the document can't drift from the code (a test checks it).
 */
export function apiReferenceMarkdown(): string {
  const groups = new Map<string, typeof allOperations>();
  for (const op of allOperations) groups.set(op.tag, [...(groups.get(op.tag) ?? []), op]);

  const who = (op: (typeof allOperations)[number]) =>
    op.auth !== 'session' ? 'public' : op.browserOnly ? 'signed-in browser' : 'session or API token';
  const cell = (text: string) => text.replace(/\|/g, '\\|').replace(/\n/g, ' ');

  const lines = [`${allOperations.length} operations. Auth: *public* (no credential), *session or API token*,`];
  lines.push('or *signed-in browser* (a session cookie; API tokens are refused).', '');
  for (const [tag, ops] of groups) {
    lines.push(`### ${tag}`, '', '| Method | Route | What it does | Auth |', '| --- | --- | --- | --- |');
    for (const op of ops) {
      lines.push(`| ${op.method.toUpperCase()} | \`${op.path}\` | ${cell(op.summary)} | ${who(op)} |`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

export const REFERENCE_START = '<!-- api-reference:start (generated by `npm run docs:api` in apps/api) -->';
export const REFERENCE_END = '<!-- api-reference:end -->';

/** Replaces the generated section of a document, keeping everything around it. */
export function withReference(document: string): string {
  const start = document.indexOf(REFERENCE_START);
  const end = document.indexOf(REFERENCE_END);
  if (start < 0 || end < start) throw new Error('reference markers not found');
  return `${document.slice(0, start + REFERENCE_START.length)}\n\n${apiReferenceMarkdown()}\n${document.slice(end)}`;
}
